import { existsSync, writeFileSync } from "node:fs";
import { AgentboxError, formatError } from "../errors.ts";

const EXAMPLE = `# agentbox example config — generated by \`agentbox init\`
# Edit this file, then run: agentbox up <this-file>.yaml [--name <name>]

# Sandbox identity. Optional — overridden by --name flag, falls back to filename basename.
name: example

# durable: persists between runs; resume with \`agentbox start <name>\`.
# ephemeral: torn down automatically when the agent exits (use --keep to preserve).
mode: durable

# Optional. Defaults to "claude-code-docker". Other built-ins: "claude-code", "claude-code-minimal".
# You can also point at a custom OCI image: "docker.io/myorg/my-template:v1".
base_template: claude-code-docker

# Repositories the agent should work with. Each lands as a sibling under
# ~/.agentbox/sandboxes/<name>/repos/<reponame>.
repos:
  # Local repo: agentbox creates a git worktree under the sandbox repos dir
  # so the agent works on its own branch without touching your main checkout.
  - source: local
    path: ~/dev/my-project
    # Optional. Defaults to agentbox/<sandbox-name>. Created from current HEAD if absent.
    branch: agent/example-feature

  # Git repo: cloned fresh inside the sandbox at startup.
  - source: git
    url: https://github.com/example/shared-lib.git
    branch: main
    # workspace (default): cloned alongside local worktrees, visible on host.
    # vm: cloned at /home/agent/repos/<name>, VM-only.
    place: workspace

# Skills to inject under /home/agent/.claude/skills/ at startup.
# Three reference forms supported.
skills:
  - coding-standards                 # bare name → ~/.claude/skills/coding-standards/
  - superpowers:brainstorming        # plugin namespaced → from plugin cache
  - ~/dev/work-skills/our-style      # explicit path

# Claude Code hooks merged into the in-sandbox /home/agent/.claude/settings.json.
# See https://docs.anthropic.com/en/docs/claude-code/hooks for the full hook reference.
hooks:
  PostToolUse:
    - matcher: "Bash"
      command: "echo \\"$CLAUDE_TOOL_INPUT\\" >> /tmp/cmd-trace.log"

# Shell commands run by agentbox at well-defined phases. Each command runs as
# \`sbx exec <name> bash -lc "<command>"\` so /etc/sandbox-persistent.sh exports apply.
lifecycle:
  # After sandbox VM exists and config is injected, before the agent starts.
  post_create:
    - "cd shared-lib && npm install"
  # Right before the agent is launched.
  pre_agent:
    - "make seed-db"
  # When the agent exits (or \`agentbox stop\` / \`agentbox rm\` is called).
  on_stop:
    - "git -C my-project status"

# Network policy entries appended to the sandbox via \`sbx policy allow network\`.
# Default sbx policy applies if you omit this section.
network:
  allow:
    - "*.npmjs.org:443"
    - "github.com:443"
    - "api.anthropic.com:443"

# Non-credential env vars written to /etc/sandbox-persistent.sh inside the sandbox.
# Use \${VAR} to read from your host environment at \`agentbox up\` time.
# For real credentials, use \`sbx secret set -g <service>\` instead.
env:
  RUST_LOG: debug
  BRAVE_API_KEY: \${BRAVE_API_KEY}

# Required services — agentbox checks they're configured via \`sbx secret ls -g\`.
# Configure each with: sbx secret set -g <name>
secrets:
  - anthropic

# Starting prompt for the agent. Inline string OR a path to a markdown file
# (auto-detected: if the value resolves to an existing file, its contents are read).
prompt: "Refactor the login module to use the new session API. Tests in tests/login.test.ts."
`;

interface InitFlags { path?: string; force: boolean }

function parseInitFlags(args: string[]): InitFlags {
  let path: string | undefined;
  let force = false;
  for (const a of args) {
    if (a === "--force" || a === "-f") force = true;
    else if (a.startsWith("--") || a.startsWith("-")) {
      throw new AgentboxError(`unknown flag: ${a}`, { fix: "Run `agentbox --help`" });
    } else if (path) {
      throw new AgentboxError(`unexpected argument: ${a}`, { fix: "Only one positional path argument is accepted" });
    } else {
      path = a;
    }
  }
  return { path, force };
}

export async function init(args: string[]): Promise<number> {
  let flags: InitFlags;
  try { flags = parseInitFlags(args); } catch (err) {
    process.stderr.write(formatError(err) + "\n");
    return 1;
  }

  if (!flags.path) {
    process.stdout.write(EXAMPLE);
    return 0;
  }

  if (existsSync(flags.path) && !flags.force) {
    process.stderr.write(formatError(new AgentboxError(`File already exists: ${flags.path}`, {
      fix: "Use --force to overwrite, or pick a different path",
    })) + "\n");
    return 1;
  }

  try {
    writeFileSync(flags.path, EXAMPLE);
    process.stderr.write(`Wrote ${flags.path}\n`);
    return 0;
  } catch (err) {
    process.stderr.write(formatError(err) + "\n");
    return 1;
  }
}
